### ISSUE TITLE
Блок 'Строки' - endless range

### ISSUE THREAD

**Issue by AlekseyPn** [hexlet-basics/exercises-ruby#70]
Приветствую, незнаю насколько важно будет, у вас в блоке есть пример:
```ruby
name[-4..]
```
Я иногда прогоняю примеры через repl.it чтобы посмотреть некоторые вещи которые меня интересуют и там данная конструкция вызывает syntax error по причине того что такой способ получения части строки валиден для  Ruby 2.6 https://ruby-doc.org/core-2.6/Range.html#class-Range-label-Endless+Ranges
И видимо на repl.it версия оказалась ниже.
Возможно конечно сейчас уже не часто используют версию ниже 2.6, просто решил сообщить об этом, вдруг будет полезно и в description к блоку стоит пояснить об этом.

**Comment by mokevnin** [comment]
Угу. Версии ниже 2.7 уже олдскул, такое только в каких-то легаси проектах.
