### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by QQpy3ko** [hexlet-basics/exercises-ruby#83]
1) https://ru.code-basics.com/languages/ruby/lessons/everything-is-object
__Функция put() выводит любые типы данных без необходимости преобразования их в строку.__
Должно быть `puts()` вместо `put()`?

2) https://ru.code-basics.com/languages/ruby/lessons/functions-definition-splat
__Splat-оператор может встречаться в определении функции только один раз и только в самом конце__
Нет ли ошибки в описании? Можно ведь и в середине Splat использовать, не только в конце или начале? Вот так:
```
def max(one_param, *numbers, another)
  numbers.max
end

puts max("что-то", 6, 31, -5, 45) # => 31
```

3) https://ru.code-basics.com/languages/ruby/lessons/functions-pipline#output
Валится тест: 
```
function#test_0001_should works [test.rb:29]:
expected --- {"1973"=>3, "1963"=>1, "1980"=>2, "2012"=>1, "1999"=>1}
```
`"2012" => 3` вроде

4) https://ru.code-basics.com/languages/ruby/lessons/functions-blocks-as-objects
`перАдавая` -> `перЕдавая`

**Comment by mokevnin** [comment]
1. fixed
2. fixed
3.Нужно считать только male
4. fixed
