### ISSUE TITLE
Тест на даты падает в последний день месяца

### ISSUE THREAD

**Issue by irkinwork** [hexlet-basics/exercises-ruby#94]
https://github.com/hexlet-basics/exercises-ruby/blob/0eabe0de654e744511d0d6eee693e3d8c5a55da8/modules/10-basics/60-classes/test.rb#L10

Кажется, это тест будет всегда падать в последний день месяца (например, сегодня)

**Comment by corsicanec82** [comment]
Поправил. Спасибо.
